### PR TITLE
add_definition -DUSING_PICOW if board is pico_w

### PR DESCRIPTION
**Pull request by fatdollar**
-libraries now have the definition as well

### CODE REVIEW

**Comment by fatdollar** [comment]
Here is a fix that addresses the pico_w issue.  I have never done a pull request with Github before so if I have not done this correctly let me know.

Basically from what I found out because cli and other directories were being added as a library the definition that was in the `hardware_build_extra` function was not being propagated to them.  So I added a conditional to the file that added the libraries and now the -DUSING_PICOW is being passed to all files.

I'm open to suggestions if this is not seen as the best way to fix the issue.  And if I need to open the pull request a different way then let me know. 

Thanks.

**Review by mcknly — CHANGES_REQUESTED** [review]
This does work however we want to avoid having hardware-specific things anywhere other than the `hardware/` directory. Take a look at [this](https://stackoverflow.com/questions/55536140/defining-preprocessor-in-modern-cmake) - maybe we want to use `target_compile_definitions` instead of `add_definitions`, since it allows scoping as `PUBLIC` and hopefully propagating the define into other libraries. If this works it should belong in `hardware/rp2040/CMakeLists.txt`. Can you test? Thanks for following up on this!

**Comment by fatdollar** [comment]
That's a good call.

I just amended my commit and made that change in `hardware/rp2040/CMakeList.txt` instead.

Probably want to do more testing but It looks like the `-DUSING_PICOW` is included in all of the files need at this point.  I've attached the build output for review if needed.  It runs on my Pico_W and the led option is still absent as it should be.

Let me know if you need anything else.

[build_target.txt](https://github.com/user-attachments/files/15811874/build_target.txt)

**Review by mcknly — APPROVED** [review]
Looks good - I have tested as well on both pico and pico_w hardware and see the expected behavior. Will merge this in. Thank for helping - if you have any other ideas for features you want to work on, feel free to start a discussion topic.

**Pull request merged**
