### PR TITLE
Unify service arrays into a simple struct array

### PR DESCRIPTION
**Pull request by nbes4**
Hello! Congratulations on such a cool project 😃, immediately had to play around with it upon reading about it. After reading into the code to start defining my own services, I noticed that the service arrays could be unified into an array containing simple structs to improve a bunch of things (see below).

Instead of maintaining three different arrays, everything goes into an array of simple structs (see `services.c`), like:

```c
 const ServiceDesc_t service_descriptors[] = {
    {
        .name = xstr(SERVICE_NAME_USB), 
        .service_func = usb_service,
        .startup = true
    },
    // more service descriptor definitions here ...
};
```

- No longer need to watch out for `service_functions` and `service_strings` to have the same order 
- No longer need to watch out for spelling errors in the `startup_services`, just a simple boolean 
- No more `(sizeof(service_strings)/sizeof(service_strings[0]))` just access `service_descriptors_length`
- No more `strcmp` to find startup services in `taskman_service` just check the `startup` bool
- [No more duplicate static variables in memory (since they are now `extern` in the header file)](https://stackoverflow.com/a/3837513)

### CODE REVIEW

**Comment by mcknly** [comment]
Thanks for the interest! Your proposed changes to the services infrastructure is logical and I like how it can simplify adding new services. I need a little more time to review, in the mean time I have created a new branch called [services-refactor](https://github.com/mcknly/breadboard-os/tree/services-refactor), can you modify your PR to target that branch? I will merge in your code so we have a sandbox before pulling into main. Thanks again for using the project!

**Comment by nbes4** [comment]
Thanks for your reply @mcknly. I changed the base branch of the PR from `main` to `services-refactor`. No stress about the review 👍

**Review by mcknly — APPROVED** [review]
Looks good. Merging into `services-refactor` branch for some testing and documentation updates (`README` etc.) before bumping to main.

**Comment by nbes4** [comment]
Awesome, let me know if you find any bugs or discuss the changes.

**Comment by mcknly** [comment]
@nbes4 I've updated the `services-refactor` branch with some additional documentation - can you pull the latest and have a look? Start with `services.h`, read through all the comments, and see if it all makes sense from a new user perspective.

Also, I put a file header in `services.c`, with your github username as author. If you want it to show anything different feel free to change and submit another PR to the branch.

If all is good I will pull it into main. Thanks again for the contribution!

**Comment by mcknly** [comment]
Here's the [direct link](https://github.com/mcknly/breadboard-os/blob/services-refactor/services/services.h) if it's easier...

**Comment by nbes4** [comment]
@mcknly [I added some comments to your commit](https://github.com/mcknly/breadboard-os/commit/18bec92e9dff3b28beeefd3f9f768a66eabc3590), don't know if GitHub notifies you of them

**Pull request merged**
